### ISSUE TITLE
How to get CB-BEFORE and CB-AFTER cursors from the response header for paginated requests

### ISSUE THREAD

**Issue by alexachim90** [mmazi/rescu#103]
Hi, 
As mentioned above, I am facing the issue of not being able to get the  CB-BEFORE and CB-AFTER cursors from the response header for a paginated request. I have tried using @NameBinding to inject interceptors, but afterward I have noticed that there are only a few annotation supported. Is there any other solution to this? 

Thanks!

**Comment by mmazi** [comment]
You are probably referring to [this discussion](https://github.com/timmolter/XChange/pull/2164#issuecomment-357755571)?

It seems rescu could easily be adapted to support regular response model classes that implement HttpResponseAware -- I'll happily accept a pull request with adequate tests.

**Comment by mmazi** [comment]
Your result model classes can now implement HttpResponseAware to access the response headers.
