### ISSUE TITLE
ProxyAuthorization header support

### ISSUE THREAD

**Issue by archenroot** [mmazi/rescu#104]
Hi, I open this issue to request support for user password authentication to proxy, meaning adding http header to request in form of ProxyAuthorization, something like:
```
System.setProperty("http.proxyHost", "myProxyServer.com");
System.setProperty("http.proxyPort", "80");
URL url=new URL("http://someserver/somepage");
URLConnection uc = url.openConnection ();
String encoded = new String
      (Base64.base64Encode(new String("username:password").getBytes()));
uc.setRequestProperty("Proxy-Authorization", "Basic " + encoded);
uc.connect();

```

**Comment by archenroot** [comment]
Some update, I forked repo and added following code into ClientConfigUtil class.

    /**
     * Adds to client config proxy basic authorization (user,password)
     *
     * @param config existing client config
     * @param proxyUser proxy user
     * @param proxyPassword proxy password
     * @return updated client config
     */
    public static ClientConfig addBasicProxyAuthorizationCredentials(ClientConfig config, String proxyUser, String proxyPassword){
        return config.addDefaultParam(HeaderParam.class, "Proxy-Authorization", digestForBasicAuth(proxyUser, proxyPassword));
    }

What else? I am happy even for hints only, can do myself otherwise....

**Comment by mmazi** [comment]
Looks fine, feel free to open a pull request.

**Comment by alinbreaban** [comment]
@archenroot did you find a solution for your issue in the end?
We tried a similar approach to what you posted on this issue but without success.

**Comment by ArLeyar** [comment]
@archenroot Same question 😄 Did you find a solution?

**Comment by archenroot** [comment]
@alinbreaban @ArLeyar sorry, I really don't remember, its quite old issue...
