### ISSUE TITLE
how to add multiple optional path params?

### ISSUE THREAD

**Issue by plopezlpz** [mmazi/rescu#110]
I have the following use case for a HTTP client: I need to include an unknown number of path params:
`GET http://something.com/1/2/3/4/5/6`
or 
`GET http://something.com/1/2`
How can I do that using this library? Thanks

**Comment by mmazi** [comment]
How are these parameter values represented in Java code? E.g. as `List<Integer>`?

Perhaps you can specify them as a single parameter of a custom type; rescu will call `toString` on it:

```
    class ParamList {
        Collection<?> params;
        ParamList(List<?> params) { this.params = params; }
        public String toString() { return params.stream().map(Object::toString).collect(Collectors.joining("/")); }
    }
```

**Comment by plopezlpz** [comment]
They are represented as a `List<String>`
I'm doing the following:
```java
List<String> params = Lists.newArrayList("1", "2", "3");
Multiple multiple = RestProxyFactory.createProxy(Multiple.class, "http://something.com");
multiple.getWithOptionalParams(params);
```
```java
@Produces(MediaType.APPLICATION_JSON)
public interface Multiple {
  @GET
  @Path("/{path:.*}")
  String getWithOptionalParams(List<String> path) throws IOException;
}
```
This will URL encode the path, resulting in: `http://something.com/1%2F2%2F3`

**Comment by mmazi** [comment]
Right. In this case, I am not sure how to help you here.

Do you need this fo XChange? Can you provide a link to the API documentation of the method you are trying to implement?

**Comment by plopezlpz** [comment]
I'm trying to support this: https://cex.io/rest-api#tickers-for-all-pairs-by-markets, the call can have between 1 and 5 possible symbols as path params:
`GET https://cex.io/api/tickers/{symbol1}/{symbol2}`
So, I can do this:
`GET https://cex.io/api/tickers/EUR` or `GET https://cex.io/api/tickers/EUR/BTC/USD` or any combination of the following: `USD`, `EUR`, `GBP`, `RUB`, `BTC`.
It is regarding this ticket: https://github.com/timmolter/XChange/issues/2385
As a workaround I can get them all and then filter accordingly, so doing this call hard coding the path:
`GET https://cex.io/api/tickers/USD/EUR/GBP/RUB/BTC` but this is not ideal since I have to hard code those and they can change, plus I'm probably getting things I don't need most of the time.

I'm familiar with okhttp3 and that would be done as such:
```java
HttpUrl.Builder urlBuilder = new HttpUrl.Builder()
                .scheme("https")
                .host("something.com");
symbols.forEach(urlBuilder::addPathSegment);

Request request = new Request.Builder().get()
                .url(urlBuilder.build()).build();

Response response = httpClient.newCall(request).execute();
String jsonResponse = response.body().string();
```
I personally think that CexIO API should not be using path params for this use case, they should be using a query param instead, like `GET https://cex.io/api/tickers?markets=EUR,BTC,USD`.

**Comment by mmazi** [comment]
You could use 5 path parameters, and leave some of them as null: `@Path("tickers/{s1}/{s2}/{s3}/{s4}/{s5}")`

This may produce an url like the following, but cex.io seems to be fine with this:
https://cex.io/api/tickers/USD/EUR///

**Comment by plopezlpz** [comment]
@mmazi ok I'll do something like that, thanks
