### ISSUE TITLE
Base64 question

### ISSUE THREAD

**Issue by timmolter** [mmazi/rescu#111]
Would it be possible to eliminate `net.iharder.Base64` and use `commons-codec.Base64` v1.11?

https://mvnrepository.com/artifact/commons-codec/commons-codec/1.11

`signpost-core` uses `commons-codec` although an older version (1.3).

There seems to be an issue related to older Base64 version; https://github.com/timmolter/XChange/issues/2402

**Comment by mmazi** [comment]
1. The XChange issue you mention has nothing to do with iharder's Base64 implementation. *Introducing* commons-codec into rescu (that you suggest) could cause further problems like this, not prevent them.
2. You can fix this in XChange by either `<exclude>`ing the commons-codec dependency from the rescu dependency, or by stating an explicit dependency on the version of commons-codec that you want to use in XChange.

(I'll probably, however, replace the iharder dependency with java.util.Base64 that is now available in Java 8, but this is an unrelated issue.)

**Comment by timmolter** [comment]
Thanks for the explanation. Yes, using java.util.Base64 would be the best thing and I believe we already did that in XChange, so removing iharder's Base64 from Rescu should be no problem. I though the issue above was related to that. commons-codec IS already used by rescu, so I was suggesting explicitly defining in the rescu POM, to update the version OR better yet, excluding it if you don't need it. What do you think?

**Comment by timmolter** [comment]
If you excluded `commons-codec` would everything still work? I'm not 100% sure but I think doing so would leave ONLY `java.util.Base64` on the classpath and no other conflicting versions. Whether everything still works would have to be experimentally tested.

<img width="385" alt="screen shot 2018-03-13 at 09 48 34" src="https://user-images.githubusercontent.com/738972/37331282-d094e9e8-26a3-11e8-95ed-1bb5123d5629.png">

**Comment by mmazi** [comment]
commons-codec is a dependency of signpost-core so I don't want to exclude it (it may be that it is required in runtime and there is no simple way to know this unless the code that uses it is actually run).

It's the XChange library that has a conflict of library version (rescu has no conflict) so this should be solved in XChange as trying to change these things in rescu is likely to cause more problems.

I've already replaced iharder's Base64 implementation with the one form java.util.

**Comment by mmazi** [comment]
What we can do in rescu, however, is to upgrade signpost-core to a newer version that would uses a version of commons-codec that is more compatible with what is used in XChange. Pull request welcome (you should create a pull request so you can confirm in advance locally that it helps). I think you should still do what I suggested in XChange (exclude or explicitly depend on commons-codec).

**Comment by timmolter** [comment]
`signpost-core` is already updated and it looks like they are not really going to release a new version soon since the last new jar was in 2012.

https://mvnrepository.com/artifact/oauth.signpost/signpost-core
