### ISSUE TITLE
SyntaxError: Unexpected token " in JSON at position 0 when using RestProxyFactory.createProxy()

### ISSUE THREAD

**Issue by makarid** [mmazi/rescu#123]
Hello, i would like to ask you if there is a way i can see a log output from the whole request message that i am sending to the server when i am using this library. I am using Xchange library and i am trying to implement a new exchange. I am trying to communicate with a node.js REST API on my localhost which needs to get a jsonString as body. Here is my implementation on the interface Airswap.class: 
@Path("/")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public interface Airswap {

        @POST
        @Path("findIntents")
        FindIntentsResponse[] findIntents(String jsonString);

Here is my implementation on the RestProxyFactory:

    protected final Airswap airswap;

    public AirswapBaseService(Exchange exchange) {
        super(exchange);
        this.airswap =
                RestProxyFactory.createProxy(
                        Airswap.class,
                        exchange.getExchangeSpecification().getSslUri(),
                        getClientConfig());
    }

And here is my implementation when i am calling the findIntent method:

    public FindIntentsResponse[] getIntents(FindIntentsObject object) throws IOException{

        String jsonString = new ObjectMapper().writeValueAsString(object);
        System.out.println(jsonString);
        return airswap.findIntents(jsonString);

    }

Is it possible to see what the server gets when i am using the RestProxyFactory,i would like to see not just the url but the whole message? I want that in order to check if there is an error on the RestProxyFactory when sending the jsonString.
I have already implement the same functionality using OKHttp library and it works without any issue.

**Comment by mmazi** [comment]
You can see request details by setting `<logger name="si.mazi.rescu" level="trace"/>` in logback.xml. See examples in rescu and XChange.

**Comment by makarid** [comment]
Thanks a lot! This helped a LOT!
