### ISSUE TITLE
rescu 2.1.0 ?

### ISSUE THREAD

**Issue by milczarekIT** [mmazi/rescu#129]
As the rescu library has a new feature: SOCKS proxy support, @mmazi  are you going to release 2.1.0 version? Rescu has been not released for over 2 years

**Comment by mmazi** [comment]
Yes, we could do a release soon. I'll see if I can do it this week.

**Comment by mmazi** [comment]
Released rescu 2.0.4:
https://github.com/mmazi/rescu/releases/tag/rescu-2.0.4

**Comment by milczarekIT** [comment]
Thanks @mmazi!
