### ISSUE TITLE
Rethink exceptions thrown as part of public API

### ISSUE THREAD

**Issue by mmazi** [mmazi/rescu#13]
See https://github.com/timmolter/XChange/issues/155

**Comment by mmazi** [comment]
So what needs to be done is that rescu should throw more descriptive exceptions instead of RuntimeExceptions. The rescu user (eg XChange) then sees these exceptions as thrown by the proxy that implements the JAX-RS-annotated interface (eg. `com.xeiam.xchange.btce.BTCE`). Note that if the exception thrown by rescu is of an unchecked type, it will directly be thrown by the proxy as-is; whereas if the exception is of a checked type, there are two possibilities: if the same exception (or its superclass or interface) is declared on the JAX-RS-annotated method, this exception will be thrown to the user, otherwise an `UndeclaredThrowableException` (wrapping the original rescu's exception) will be thrown.

All invocations of a proxy provided by rescu that implements a JAX-RS-annotated interface are I/O operations (the involve accessing a remote server via HTTP(S)) so it makes some sense that `IOException`s are always expected and handled here by the caller (eg. there may be no network connectivity, the server may be down etc.)

I see two options here:
1. Rescu throws unchecked exceptions; the user should then somehow know this (probably from the docs, or from experience after seeing a stack trace in the logs), catch the exception and handle it.
2. Rescu throws checked exceptions (eg. IOException or subclasses). The user has two options: 
   - a. They can declare `throws IOException` on all methods on the JAX-RS-annotated interface. All calls to these methods must then handle or declare IOException.
   - b. They don't declare IOException. This is quicker to implement, but in case of an error an UndeclaredThrowableException will be thrown which is harder to handle. When a user will see this in the log, they probably won't know that the correct way to handle this is to declare `throws IOException` on the interface method, but might catch UndeclaredThrowableException, which is not a good approach.

Option 1 is the most agile because it doesn't impose any coding requirements on the user (that they should read about in the docs) and no verbose try/catch clauses by default. The user can implement this if they expect IOExceptions to happen, or when the encounter one in the logs.

Option 2 requires the user to read the docs ("you should declare `throws IOException` on all interface methods") and then handle exceptions (which a decent application will have to do anyway since the server may really be down or network not available). This is better for serious applications -- if users read the docs. If they don't, we're left with 2.b which is the worst (though not very much worse than 1).

@timmolter, do you have any opinion on this? One minor thing to consider here is that changing this from 1. to 2. or vice versa in the future will break rescu's public API (ie. break backwards-compatibility). There are few users of rescu currently so this is not a major issue.

I'm most inclined to go with 1. since it is the most agile and entails the least changes for now. Rescu's public API changes often anyway.

**Comment by timmolter** [comment]
Well thought out, @mmazi. I agree. I wouldn't want to force handling checked exceptions for every JSON call. The way I use XChange mostly is to make individual REST calls wrapped in their own threads, and if an exception occurs the thread basically just dies and the app continues unaffected. So for me Option 1 works very well. 

I think I will just add to all XChange interface method declarations `throws RestJsonException`, so that the alert programmer knows that these might occur and they can adjust their program accordingly.
