### ISSUE TITLE
Snapshot version not correct?

### ISSUE THREAD

**Issue by timmolter** [mmazi/rescu#14]
It looks like the current develop version is 1.2.0-SNAPSHOT. Shouldn't it be 1.2.1-SNAPSHOT since the last release was 1.2.0?

**Comment by timmolter** [comment]
also, it would be nice if you deployed the javadocs and source as well. :)

**Comment by mmazi** [comment]
Done. Version changed to 1.3.0-SNAPSHOT since it contains public API changes. Sources and javdocs jars are now built in travis build.
