### ISSUE TITLE
sending binary data

### ISSUE THREAD

**Issue by premek** [mmazi/rescu#141]
Hi, 
I'm having some trouble sending binary content in http request body.

For bytes < 0x80 everything works fine but if I send one 0x80 byte, the content-length is computed incorrectly (I think - or the content is encoded incorrectly) 

It's probably somehow caused by conversion to String and back to bytes when sending.

I haven't discovered where exactly is the issue, I'll try to provide more info when I have more time (and if supporting this is not out of scope for this project).

Would it make sense to be able to provide a byte array directly that wouldn't be converted to String and back to byte array?

**Comment by mmazi** [comment]
Can you write a PR with a test case?

**Comment by premek** [comment]
Today I tried to reproduce this issue I filled some time ago and I can see I didn't do a good job describing the issue.

I remember I was trying to send image data (e.g. a JPEG) in a request. It was raw bytes, not base64 or anything like that. Which means it was probably not inside JSON.

So I was probably trying to abuse the `ToStringRequestWriter` with `MediaType.TEXT_PLAIN`.

That way I would have to convert my `byte[]` to `String` somehow, call a method with String argument on the proxy and in `HttpTemplate#send` the argument is converted to `byte[]` using **UTF-8**.

That means I'd have to use UTF-8 to convert my input data if I wanted it to be converted back to the same `byte[]`.

Problem is arbitraty data cannot be converted to UTF-8 and back, example:
```java
// OK:
assertEquals(new byte[]{(byte) 0x01}, new String(new byte[]{(byte) 0x01}, StandardCharsets.UTF_8).getBytes(StandardCharsets.UTF_8))

// Fails:
assertEquals(new byte[]{(byte) 0x80}, new String(new byte[]{(byte) 0x80}, StandardCharsets.UTF_8).getBytes(StandardCharsets.UTF_8));

``` 


Questions:
- It's not possible to add custom `RequestWriter`s to `RequestWriterResolver`, right?
- Is my use case above out of scope for Rescu? If yes, this issue can be closed

**Comment by mmazi** [comment]
Answers:

- You're right, support for only `application/x-www-form-urlencoded`, `application/json`, and `text/plain` is hard-coded.
- It seems so. Rescu is meant primarily for json requests and responses. I stated this more clearly in the README now.

**Comment by premek** [comment]
Thank you, closing this
