### ISSUE TITLE
Upgrade to jakarta.ws.rs-api 3.x

### ISSUE THREAD

**Issue by ppalaga** [mmazi/rescu#142]
Note that `jakarta.ws.rs-api` 3.x uses `jakarta.ws.rs` Java package names instead of `javax.ws.rs` thus being backwards incompatible with  jakarta.ws.rs-api 2.x

It would be nice to have this to be able to use ResCU on Quarkus 3.x.

**Comment by mmazi** [comment]
Care to create a pull request?

**Comment by ppalaga** [comment]
> Care to create a pull request?

Sorry, I do not feel like I can deliver it in a reasonable time and quality. I heart of ResCU today for the first time.

**Comment by mmazi** [comment]
Done and released in version 3.0. Thanks!

**Comment by ppalaga** [comment]
Thanks a lot, @mmazi !
