### ISSUE TITLE
JSONUtils Question

### ISSUE THREAD

**Issue by timmolter** [mmazi/rescu#15]
After updating to 1.4.0-SNAPSHOT, I noticed another place that might need to be cleaned up a bit in ResCU: the getJSONString method in `JSONUtils`. Like the other methods in the class, should it throw `RestJsonException` rather than `JsonProcessingException`?

**Comment by mmazi** [comment]
JSONUtils has three methods of which only one (getJsonObject) is ever used in rescu, and it is a one-liner (the rest is exception handling boilerplate that probably shouldn't be there).

So I decided to just scratch JSONUtils from rescu and use ObjectMapper directly.

**Comment by mmazi** [comment]
Here's the commit: https://github.com/mmazi/rescu/commit/5c223056d4443f558bca3f8a99779d4ee1d29f48

**Comment by timmolter** [comment]
sounds good. I'll check it out. I think XChange used some of those methods directly though.

**Comment by mmazi** [comment]
You can copy JSONUtils into XChange and use it there. But I'd recommend just inlining all those methods without the boilerplate (ie. using ObjectMapper directly).
