### ISSUE TITLE
How to handle Response Codes other than 200?

### ISSUE THREAD

**Issue by jpe42** [mmazi/rescu#18]
I'm making a HTTP Post that has a successful return code of 201 (created).  Is there a recommended way to handle this since HttpTemplate only accepts response code 200?

https://github.com/mmazi/rescu/blob/develop/src/main/java/si/mazi/rescu/HttpTemplate.java (line 117)

Context of usage: https://github.com/timmolter/XChange/issues/271

**Comment by mmazi** [comment]
This was indeed a bug in rescu, thanks for reporting!
