### ISSUE TITLE
How to annotate POJO for rest serialization 

### ISSUE THREAD

**Issue by jpe42** [mmazi/rescu#21]
Coinbase accepts JSON objects for parameters, i.e., https://coinbase.com/api/doc/1.0/accounts/generate_receive_address.html.  I'm trying to figure out how to create a POJO so that it will be serialized to JSON, but it looks like it will always just use toString()?  Do I have to have the toString produce JSON representing the object?

I was hoping to be able to do something like this:

public class CoinbaseCallbackUrlParam {
  public String callback_url;
  public String label; 
.... }
...
@POST
@Path("account/generate_receive_address")
CoinbaseReceiveAddress generateReceiveAddress(@FormParam("address") CoinbaseCallbackUrlParam callbackUrl,...);

**Comment by mmazi** [comment]
You can do it exactly as you want it to, just drop the `@FormParam` annotation from the method parameter. If I'm reading the docs correctly, the JSON shouldn't be submitted as a form parameter, but as the whole HTTP request body.

I'll try to find an example in XChange where this is already used.

**Comment by mmazi** [comment]
Also, the method (or the whole interface, if all methods are such) should be annotated with `@Consumes(MediaType.APPLICATION_JSON)`.

For an example where this is already done, see https://github.com/timmolter/XChange/blob/develop/xchange-bitfinex/src/main/java/com/xeiam/xchange/bitfinex/v1/BitfinexAuthenticated.java .

So, in general, to create a REST HTTP request where the HTTP request body is a single JSON-serialized object, you need to create an interface method that accepts `application/json` and has a single non-annotated parameter whose class is JSON-serializable (eg. annotated with jackson annotations). Such method can have no `@FormParam` parameters (but may have `@QueryParam`s, `@PathParam`s and `@HeaderParam`s).

**Comment by jpe42** [comment]
Nice! worked like a charm.  Thanks for the detailed response/example, made it super easy to implement.
