### ISSUE TITLE
Change the default content-type header?

### ISSUE THREAD

**Issue by timmolter** [mmazi/rescu#22]
Right now, the default content-type header is `application/x-www-form-urlencoded`. Using the `Consumes` annotation, we can set that header. The problem is though that what if I'm sending no request body as is the case for many public marketdata requests? That header shouldn't even be sent. 

I think if we were designing this from the beginning, you'd have to explicitly set the `Consumes` annotation for all requests where containing a request body, and the default is no body and no content-type header. There is no `Consumes` annotation for "no body".

If we switch it now, ResCU isn't backwards compatible, but it's strange how the default behavior is now.

What do you think?

**Comment by mmazi** [comment]
I agree, default should be no header.

There are some other default headers, I'll have a look at all of them.

We need to test how many XChange exchange integrations this will break (but should be simply fixable with `@Consumes`).

**Comment by timmolter** [comment]
Cool, I already changed the rescu code. Should I push it and then you can have a look? I can then make all necessary changes in XChange.

**Comment by mmazi** [comment]
Sure, go ahead -- thanks!

**Comment by mmazi** [comment]
Oh, the version should probably be changed because of the non-backwards-compatibility. Can you make a pull request instead?

**Comment by timmolter** [comment]
Whoops, too late. Sorry about the formatting too. I think for now on, I'll work on my own fork and submit a pull request, with my code formatting turned off too.

**Comment by timmolter** [comment]
Can you change the version?

**Comment by mmazi** [comment]
Thanks, I'll finish this.

**Comment by mmazi** [comment]
Ugh, if you don't mind, I'll revert your commit in develop and re-do it without the formatting changes :). This change affects so many lines and changes their history in `git blame`.

You'll have to force merge though.

**Comment by timmolter** [comment]
Yeah, sorry about that. Do I need to do anything? I'm going to create my own fork of rescu right now.

**Comment by mmazi** [comment]
No worries, I'm on it already.
When you pull or merge into your existing develop branch, you'll have to force it (-f). Your fork will be fine since it will already contain my non-fast-forward change.
It's not completely necessary to create your own fork as you can push branches into my repo and request pull there. But it is probably cleaner if you do it in your own repo. Whichever you prefer.

**Comment by mmazi** [comment]
Done; please test with XChange to see if this is what you need.

Note that we still always send the `Accept: application/json` header since rescu always interprets the response body as json (no support for other formats).

**Comment by timmolter** [comment]
Thanks, I'll test later tonight.
