### ISSUE TITLE
Configuring authentication when creating proxy client.

### ISSUE THREAD

**Issue by newjam** [mmazi/rescu#23]
I'm writing an API using jax-rs annotations. I want to create a proxy client in an Android application. The proxy client resource and the server side rest resource implementations  are using shared interfaces so there is no mismatch between the client and the server. 

I'm securing the API with http basic authentication. The problem is, the resources methods do not have parameters annotated with @HeaderParam("Authorization") because that is handled in a filter before each resource invocation, and not per resource. Other jax-rs proxy clients, such as jersey's, apache's, and rest-easy's configure authentication in separately for example, [in jersey](https://jersey.java.net/apidocs/2.6/jersey/org/glassfish/jersey/client/proxy/package-summary.html):

``` java

HttpAuthenticationFeature authentication = HttpAuthenticationFeature.basic(username, password);

WebTarget target = ClientBuilder.newClient(
            new ClientConfig().register(authentication))
            .target(baseUrl);

MyResource proxy = WebResourceFactory.newResource(MyResource.class, target);
```

I like rescu because it is Android compatible, but I would like to be able to configure authentication when creating the proxy client, not when invoking a method. Thanks for your work on rescu. Let me know if there is a workaround for this, or if this could be supported.

**Comment by mmazi** [comment]
Thanks for pointing this out. I'll see if I can implement something quickly.

Rescu currently has no support for JAX-RS 2.0 (like WebTragets, Features, Config etc.).

I'm thinking of creating a Configuration class (probably not (yet) an implementation of `javax.ws.rs.core.Configuration`) that would for now just add the specified parameters to every request. Do you think this would work for you?

**Comment by mmazi** [comment]
I've done it as I've suggested above; basically you need to do this:

```
    ClientConfig config = ClientConfigUtil.addBasicAuthCredentials(new ClientConfig(), "Aladdin", "open sesame");
    RestProxyFactory.createProxy(Service.class, url, config);
```

Let me know if this helps!

**Comment by newjam** [comment]
Hi!
This works great, and fits my needs perfectly.
Thanks for this improvement.

P.S. sorry for taking my time responding.

**Comment by DiiaanaD** [comment]
Hello @mmazi 

I was trying to solve the same problem (use a proxy that needs authentication)  and the solution from above doesn't work.

The headers are set on ClientConfig but they don't seem to be populated on the proxy also.
Any idea?

Thanks,
Diana
