### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by ObsessiveOrange** [mmazi/rescu#31]
Any chance that a connection timeout could be added, in addition to the readTimeout? I'd be happy to do the necessary changes.

**Comment by timmolter** [comment]
@ObsessiveOrange check out the readme file for doing this. It's already possible.

**Comment by ObsessiveOrange** [comment]
@timmolter I could only find the `rescu.http.readTimeoutMillis`, but nothing on connection timeout. Am I missing something?

**Comment by timmolter** [comment]
oh sorry. I missed that detail!

**Comment by ObsessiveOrange** [comment]
No problem :) The reason I would like that feature added is that I find most of the failed REST requests I have are actually from the connection phase, rather than the read phase. Cutting it short and restarting the connection usually works, so that's my goal with all this.

**Comment by mmazi** [comment]
Merged - @ObsessiveOrange , thanks for contributing!

**Comment by ObsessiveOrange** [comment]
@mmazi My pleasure. Does this get automatically pushed to maven central? I'm not seeing the changes reflected in my project.

**Comment by mmazi** [comment]
The changes are in version `1.6.1-SNAPSHOT`, are you using this version?

Everything seems fine to me: [the travis build](https://travis-ci.org/mmazi/rescu/builds) was successful and the artifacts are in [the Sonataype snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/com/github/mmazi/rescu/1.6.1-SNAPSHOT/).

**Comment by ObsessiveOrange** [comment]
Ahh, I see. sorry, only noticed the 1.6.0 build on maven central. I'll
switch it over to the snapshots.

Thank you!

**Comment by timmolter** [comment]
@ObsessiveOrange feel free to update the develop branch of XChange too with `1.6.1-SNAPSHOT`.
