### ISSUE TITLE
Status Code 500, but need the JSON

### ISSUE THREAD

**Issue by timmolter** [mmazi/rescu#4]
Try out: com.xeiam.xchange.examples.mtgox.v2.service.account.WithdrawalFundsDemo.java in xchange-examples.

The status code returned is 500 which causes an HTTPException, but I would like to have the JSON it returns to log the error message.

Any ideas?

**Comment by timmolter** [comment]
This is the case in MtGoxPollingTradeService.cancelOrder as well. I think there might need to be some mechanism to accept a certain return code or range of return codes within the ResCU API.

What do you think?

**Comment by mmazi** [comment]
I've changed rescu's behavior on non-200 http statuses: an exception is now thrown that contains the status code and the error stream (the body of the request) that can be subsequently checked by the calling library:

https://github.com/mmazi/rescu/commit/2e34c24d636809c6f10f7c107e6c585924726b43

I think an elegant solution would be to provide support for Jackson-annotated exception on the API-interface methods. I will try that.

**Comment by mmazi** [comment]
@timmolter, try this to see how the cancel order example behaves with the new code (you should git pull and mvn install rescu, of course):

http://pastebin.com/MhacAYvR

**Comment by timmolter** [comment]
This isn't exactly what I was thinking, but it works. Could you make the HttpStatusException class have a String field instead of an InputStream? I can do it if you want.

What would be a better solution would be for me to be able to specify, perhaps with an annotation, that I accept code=500 returns and it should parse the json into my DTO the same as if it was a 200 return value. Know what I mean??

I know it's a bit non-standard, but it would be a cool feature.

**Comment by mmazi** [comment]
Actually, I've made quite some progress on the solution I mentioned above as elegant; I hope you'll like it.

And yes, it includes changing HttpStatusException to have a String field :)

**Comment by mmazi** [comment]
I've pushed the changes into rescu; you can try it here and see if this suits your needs:
https://github.com/timmolter/XChange/commits/rescu-with-exceptions

I'm finishing for today; if this is what you need, I'll release rescu tomorrow.

**Comment by timmolter** [comment]
Yup, very cool. The only drawback is that I have to now use try catches, but this is really great and a good general solution. Good thinking!
