### ISSUE TITLE
ValueFactory (nonce) - refactor

### ISSUE THREAD

**Issue by mmazi** [mmazi/rescu#41]
Refactor the merge in #40, if needed. See #40 for details.

**Comment by mmazi** [comment]
See also #45 .

**Comment by mmazi** [comment]
@rafalkrupinski , thanks again for the ValueFactory contribution.

Before releasing this addition in the next version though, I'd still at least like to make it much clearer in the code that the purpose of ValueFactory is synchronization to avoid potential misuses. I feel the interface name should reflect this purpose, since the interface itself (the only method it contains) doesn't reflect that this is about synchronization at all.

I suggest to rename ValueFactory to SynchronizedValueFactory. I'll do the necessary minor refactoring in XChange too. @timmolter and @rafalkrupinski , let me know if this sounds fine to you guys.

**Comment by timmolter** [comment]
I'll let @rafalkrupinski comment on your question.

One thing I wanted to say was that I think `NonceFactory` should be renamed to something like `CurrentTimeMillisNonceFactory` or something non-generic as it now is, to represent it's nature a bit more. `ValueFactory` could also be renamed to `NonceFactory` with a `createNonce` method. 

In addition, you might want to put it all in a separate package with all the factories (which don't exist yet). @rafalkrupinski Are there any more factory implementations in XChange that we could move over to rescu?

**Comment by rafalkrupinski** [comment]
I'm OK with SynchronizedValueFactory. I thought about SyncValueFactory - it's shorter but your version sounds better to me.

NonceFactory was intended as a default implementation.
Four possible common implementations come to my mind, this is how I'd see them named:
- AtomicInteger iniialized with current time/250 (or a ctor paramter) - IntNonceFactory,
- AtomicLong initialized with current time - LongNonceFactory
- long current time millis - LongTimeNonceFactory (currently NonceFactory)
- current time/250 as int IntTimeNonceFactory

[division by 250 came from some exchange implementations, is it a good idea?]

Maybe we don't need all four of them, two would suffice - long and int version.

Nonce is specific to exchanges, not a part of mapping/transport layers. I think the implementations should be in xchange-core, sparate package or not.
Edit: This is also why the interface is called ValueFactory, not a NonceFactory

**Comment by mmazi** [comment]
I agree with the above comments. I'll rename the interface, rename NonceFactory to LongTimeNonceFactory and move it to xchange-core. Will do this now, will push to both repos shortly.

**Comment by mmazi** [comment]
@timmolter , do you agree that factory implementations should be moved to xchange-core? What package do you suggest for the implementations?

**Comment by timmolter** [comment]
Yeah, that's fine. You can put them wherever you think is best.

**Comment by timmolter** [comment]
Thanks @mmazi and @rafalkrupinski !
