### ISSUE TITLE
Additional triggers for exception parsing

### ISSUE THREAD

**Issue by mmazi** [mmazi/rescu#47]
Currently, [custom exception parsing](https://github.com/mmazi/rescu/wiki/Exception-handling#mapping-http-errors-to-exceptions) is alway triggered only by a non-OK HTTP response code. Some other triggers should probably be added, like unsuccessful parsing of the json as the normal response object.

**Comment by timmolter** [comment]
Yeah, that would be a great feature. Since there is no real standard that webservices adhere to, everyone makes up their own error response system. The case that rescu doesn't yet cover is a system where all responses are 200, but the JSON returned is different.

**Comment by timmolter** [comment]
@mmazi Have you had any recent thoughts on this? How could it be implemented generically? Any ideas?

**Comment by mmazi** [comment]
Quoting @timmolter :

> The case that rescu doesn't yet cover is a system where all responses are 200, but the JSON returned is different.

Covering this case should be easy so I'll do this now. If there are any other concrete suggestions for conditions when response should be treatead and parsed as an Exception, please point them out.

**Comment by mmazi** [comment]
I've added this option now. See [the wiki](https://github.com/mmazi/rescu/wiki/Exception-handling#triggering-exception-parsing-based-on-json-content) for how it can be used.

I also considered using [json schema](http://json-schema.org/) to let the user determine which responses should be parsed as exceptions, but this seems to be overkill in terms of introduced dependencies (https://github.com/fge/json-schema-validator) and requiring the user to learn a new language. The way it's implemented now the user can simply validate the returned data in Java code in the constructor, which makes sense anyway.

Note that json in general (and Jackson in particular, as far as I could see) doesn't provide any facilities for validating schema or otherwise validating that the data conforms to some rules.

**Comment by mmazi** [comment]
I'd appreciate it if someone could try using this in/with XChange to see if it fits the needs. I'll be glad to help, time permitting.

**Comment by mmazi** [comment]
I've added another change: response body will be parsed as exception also when a `JsonMappingException` is thrown. In this case, the user doesn't even have to do anything.

Note that now the [wiki](https://github.com/mmazi/rescu/wiki/Exception-handling) is slightly outdated, and that `HttpStatusIOException` that may be thrown by rescu is inappropriately named and may carry a misleading message. I'll fix this soon, hopefully.

**Comment by mmazi** [comment]
Wiki has been updated too.
