### ISSUE TITLE
Can you release 1.7.1?

### ISSUE THREAD

**Issue by timmolter** [mmazi/rescu#49]
Sorry to ask again so soon!

**Comment by mmazi** [comment]
I'll do this this evening or tomorrow morning.

**Comment by timmolter** [comment]
thanks much.

**Comment by mmazi** [comment]
Released; should soon appear [in Maven Central](https://search.maven.org/#search%7Cga%7C1%7Crescu).

**Comment by timmolter** [comment]
thanks!
