### ISSUE TITLE
Synchronized write and producing JSON body

### ISSUE THREAD

**Issue by rafalkrupinski** [mmazi/rescu#51]
I've just discovered a problem with SynchronizedValueFactory: when a client produces JSON body (@Consumes(APPLICATION_JSON)) then all data not passed as a header must be in a single unannotated parameter. If that object contains embedded SVF, RestInvocationHandler won't handle it at all, leaving it to the Jackson serializer.

There are two problems with that:
1. Jackson won't serialize SVF
2. ...and even if it did, RestInvocationHandler won't call the method in a synchronized block.

I see these possible solutions:
1. Let RestInvocationHandler search for SVF inside the unannotated parameter and enable synchronization if found. Also, add serializer for Jackson.
2. Add a new ResCU annotation `@Synchronized` to methods and rely on it to enable synchronization; stop looking for SVF in parameters. Because rescu would use exchange proxy object as the monitor, XChange would have to be modified, to keep single proxy instance per exchange (currently instance per PollingService).

I'd go for no. 1.

**Comment by mmazi** [comment]
Any idea how to implement 1. efficiently?

**Comment by rafalkrupinski** [comment]
No, I didn't think efficiency is important, since we're dealing with network communication. Anyway, it could be done once and memorized

**Comment by mmazi** [comment]
>  keep single proxy instance per exchange

This should probably be _single instance per exchange user_? I think generally exchanges require that nonce be strictly increasing _per user_ (or per API key).

**Comment by rafalkrupinski** [comment]
I meant "per exchange client object"

**Comment by rafalkrupinski** [comment]
here is some work in progress 2a5fecf1e68e3bb2a71b554d8d499db7822550c3
