### ISSUE TITLE
Unable to parse as custom Exceptions when Android app is obfuscated

### ISSUE THREAD

**Issue by zholmes1** [mmazi/rescu#53]
My Proguard configuration is set up to keep rescu, XChange, Jackson, and Hamcrest. I've decompiled my app and confirmed that the name of the error message ("String message") has remained untouched, even after obfuscation. So why would rescu be unable to parse the response as `BitfinexException`? Might there be any other libraries that are used for rescu's exception handling that I need to exclude from obfuscation?

**Comment by mmazi** [comment]
Hi @zholmes1 ,
Please see [dependencies](https://github.com/mmazi/rescu#dependencies). Hamcrest is only needed for testing, and rescu doesn't depend on XChange, so these two should not affect rescu.
Hope this helps. If not, please provide some more info, like error messages etc.

**Comment by zholmes1** [comment]
Oddly enough I was getting an UndeclaredThrowableException, with the HttpStatusIOException as the undeclared throwable. I tried excluding everything but my own package from obfuscation/optimization, and while not ideal, it seems to have done the trick (for now).

**Comment by mmazi** [comment]
> Oddly enough I was getting an UndeclaredThrowableException, with the HttpStatusIOException as the undeclared throwable.

Try also declaring `IOException` on your methods. There are cases when rescu can't parse the response as your declared exception (eg. there is no response body, or appropriate constructors are not found etc.) and it will throw an `HttpStatusIOException` in this case. Moreover, an `IOException` could be thrown for other reasons in the underlying code.

I think it's good practice to always declare `IOException` on your methods. You'll have to handle it in the calling code, but an `IOException` when calling outside service is something you should think about and handle anyway.

**Comment by zholmes1** [comment]
IOException was already declared, which is why I was having a very hard
time figuring out the issue.
