### ISSUE TITLE
How to update to newest version in Eclipse/Maven?

### ISSUE THREAD

**Issue by zholmes1** [mmazi/rescu#56]
I am developing for XChange in Eclipse, and I have the project imported as a Maven project. I need to be able to use the newest version to deal with Netagio's API, but I can't seem to get ResCU to update to the newest version with the necessary commit which removes the byte order mark. I've edited xchange-core's pom.xml to use rescu version 1.7.2-SNAPSHOT, which is reflected in my Maven dependencies. However when I download the source and open HttpTemplate.class I still see the old code in there. Any ideas?

**Comment by timmolter** [comment]
update the rescu version in pom.xml under the parent directory. I will do it.

**Comment by mmazi** [comment]
There's a `-U` switch for `mvn` to update dependencies.

Or perhaps set `upatePolicy` for the repo.

```
  <repositories>
    <repository>
      <snapshots>
        <updatePolicy>always</updatePolicy>
      </snapshots>
    </repository>
  </repositories>
```

Or try simply deleting  `~/.m2/repository/com/github/mmazi/rescu/1.7.2-SNAPSHOT` and rebuilding (`mvn clean install`).

**Comment by zholmes1** [comment]
Worked like a charm. Thanks @timmolter and @mmazi!
