### ISSUE TITLE
Top level associative arrays

### ISSUE THREAD

**Issue by smnz** [mmazi/rescu#59]
I have a service I would like to interface with that returns JSON in this structure:

{"1":{"foo":123},
 "2":{"foo":456},
 "3":{"foo":789}}

This is an associative array where the keys also happen to be an array index.  It's also at the top level, rather than assigned to some variable.

Just wondering if there is some way with rescu to deal with this sort of deserialization?

Many thanks.

**Comment by mmazi** [comment]
I can't think of a way how to map this to a sensible Java data structure (like a List or a Map); but I'm actually not very experienced in Jackson, and this is actually a Jackson question.

I suggest you try asking this question at a Jackson forum or issue tracker.

**Comment by mmazi** [comment]
@smnz , have you resolved this issue? Do you still think anything can be done about it in rescu? Or can this issue be closed?

**Comment by smnz** [comment]
Sorry, yes, please close it. I worked around the difficulty for now.
