### ISSUE TITLE
Merge JacksonConfigureListener and JacksonObjectMapperFactory

### ISSUE THREAD

**Issue by mmazi** [mmazi/rescu#88]
JacksonObjectMapperFactory was introduced in #87; it hasn't been merged with JacksonConfigureListener due to backwards compatibility reasons. They serve the same purpose though and should be merged; possibly one of them should be deprecated first.

**Comment by mrmx** [comment]
I agree and could merge it unless you'd like to implement it ;)

**Comment by mmazi** [comment]
If you have an idea how to merge them and still keep backwards compatibility, I'll be happy review the PR. (Sorry for the late response on #87, I was on vacation.)

**Comment by mrmx** [comment]
Sure! I'll start right now! ;)
