### ISSUE TITLE
Use of deprecated RestInvocation#getAllHttpHeaders

### ISSUE THREAD

**Issue by matthewdowney** [mmazi/rescu#91]
[Line 152 of `RestInvocationHandler`](https://github.com/mmazi/rescu/blob/develop/src/main/java/si/mazi/rescu/RestInvocationHandler.java#L152) calls the [`RestInvocation#getAllHttpHeaders`](https://github.com/mmazi/rescu/blob/develop/src/main/java/si/mazi/rescu/RestInvocation.java#L244) method, and there's a javadoc comment noting that it's deprecated and that [`RestInvocation#getHttpHeadersFromParams`](https://github.com/mmazi/rescu/blob/develop/src/main/java/si/mazi/rescu/RestInvocation.java#L258) should be used instead.

But it looks like use of the new method results in the omission of the `Content-Type` header. The new method will simply use the default headers defined in `HttpTemplate`, which essentially just hard-codes a default `Accept` header and nothing more.

``` java
// == HttpTemplate.java line 93 ==
defaultHttpHeaders.put("Accept-Charset", CHARSET_UTF_8);
// defaultHttpHeaders.put("Content-Type", "application/x-www-form-urlencoded");
defaultHttpHeaders.put("Accept", "application/json");
// User agent provides statistics for servers, but some use it for content negotiation so fake good agents
defaultHttpHeaders.put("User-Agent", "ResCU JDK/6 AppleWebKit/535.7 Chrome/16.0.912.36 Safari/535.7"); // custom User-Agent
```

It seems like the correct thing to do would be to check the request type, and then insert the value of the `@Consumes` annotation if present into the correct header. Something like

``` java
    // == RestInvocation.java line 258 ==
    public Map<String, String> getHttpHeadersFromParams() {
        Map<String, String> headers = getParamsMap().get(HeaderParam.class).asHttpHeaders();
        if (methodMetadata.getReqContentType() != null && methodMetadata.getHttpMethod().equals(HttpMethod.POST)) {
            headers.put("Content-Type", methodMetadata.getReqContentType());
        } else if (methodMetadata.getReqContentType() != null && methodMetadata.getHttpMethod().equals(HttpMethod.GET)) {
            headers.put("Accept", methodMetadata.getReqContentType());
        }
        return headers;
    }
```

I know I'm jumping the gun a little because this isn't yet in the release, but I'm wondering about the implementation strategy because I was troubleshooting a bug from the missing header in my own fork--and thought that there was a chance that this could be a bug that someone else would have to solve here.

**Comment by mmazi** [comment]
Thanks for reporting. I'm clarifying a few things below.

> [the RestInvocation#getAllHttpHeaders method] is deprecated and that RestInvocation#getHttpHeadersFromParams should be used instead.

The `getAllHttpHeaders` is deprecated _as a public API_ method; the javadoc says that it will be made package local, i.e. it will cease to be part of the public API, but the method itself will be kept as it is still the correct method to be used internally by rescu.

> The new method

It's not new, it's just the method that should be used by library users (eg. for creating digests).

> ... will simply use the default headers defined in HttpTemplate

This is incorrect: it actually uses the `@HeaderParam`-annotated parameters of the API method (and doesn't use the default headers from HttpTemplate at all):

```
public Map<String, String> getHttpHeadersFromParams() {
    return getParamsMap().get(HeaderParam.class).asHttpHeaders();
}
```

>  this isn't yet in the release

I'm not sure what you mean by this.

Generally, I'm at a loss though: I don't understand what exactly is the issue you're having (or had). Can you describe your problem more precisely? Thanks.

**Comment by mmazi** [comment]
Closing as this is old. If necessary, please reopen and reply to the above questions.
