### ISSUE TITLE
Can you push a new release to Maven Central?

### ISSUE THREAD

**Issue by timmolter** [mmazi/rescu#92]
Would be great! I'm going to release a new XChange version.

**Comment by mmazi** [comment]
Sure, working on it. Need to wait for my keys to sync tho, the previous one has expired.

**Comment by timmolter** [comment]
You could update jackson right away too. :) `2.8.3`

**Comment by mmazi** [comment]
Oops, too late for jackson. How important is this?

**Comment by timmolter** [comment]
Not important. No worries. :)

**Comment by mmazi** [comment]
Released 1.9.0.
