### ISSUE TITLE
problem with reading  array like: [1,2,3,4,5,6] as response

### ISSUE THREAD

**Issue by wonkytonky** [mmazi/rescu#93]
hi, i'm trying to read an array like this: 
[0.00072932,0.0007,30,8216.4406985,0.00071162,2,4339.58117193,0.00000919,0.0131,0.00071162,4947669.67309485,0,0]

from https://api.bitfinex.com/v2/ticker/fUSD   (it works in browser for quicktest)

after some debugging .. i think it might be fixed 
by allowing this in the objectmapper
seserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS

maybe i'm missing somthing  
help is welcome. 

thanks

**Comment by mmazi** [comment]
Please report what the problem is (error message etc.).

It is possible to use `SerializationFeature`s by suppling a config -- search XChange for "SerializationFeature" for examples.

I can provide more info tomorrow.

**Comment by wonkytonky** [comment]
thanks.; i'll already try to make it work  on my side

**Comment by mmazi** [comment]
Is there anything I can still do regarding this issue? Please reopen if so.
