### ISSUE TITLE
Support http method PATCH

### ISSUE THREAD

**Issue by EricAnderson1000** [mmazi/rescu#95]
Many APIs now support the operation PATCH for partial replacement of resources. 
See https://tools.ietf.org/html/rfc5789

I would be happy to work on this feature.

**Comment by mmazi** [comment]
That's great to hear! I'll be happy to review your pull requests, or provide any other help you might need.

**Comment by cymp** [comment]
@EricAnderson1000 did you get a chance to make progress on this

**Comment by EricAnderson1000** [comment]
Not quite yet. Hope to get to this feature later this week. Working the XChange PR right now.

**Comment by mmazi** [comment]
Merged in #100 .
