### ISSUE TITLE
New release for XChange?

### ISSUE THREAD

**Issue by timmolter** [mmazi/rescu#99]
I'd like a new release containing my recent PR and some of the other recent ones requiring Java 8. @mmazi Can we make this happen?

**Comment by mmazi** [comment]
I've been on a longer vacation, I'll get on this next week.

I'll probably release support for Java 8 in rescu with a higher minor
version, but I have to look into the issue.

**Comment by mmazi** [comment]
I've released rescu 2.0.0 that uses Java 8. 

We can continue Java 7 support in the java-7 branch if needed; any such released versions will be called 1.9.x.

@timmolter I just noticed, however, that you might need a release with #95 included? If so, I can merge #95 and release it in 2.0.1 in a few days.

**Comment by timmolter** [comment]
Yes, would be good! Thanks!

**Comment by mmazi** [comment]
Done.
